### ISSUE TITLE
Can't see .svg thumbnails in Onedrive's folder

### ISSUE THREAD

**Issue by dehciappina** [maphew/svg-explorer-extension#1]
### Problem
The svg explorer extension is not working inside the onedrive folder, where I synchronise my work to the cloud.

### Solution
Go into Settings and disable the _Save space and download files as you use them_ option.

With the option enabled files are uploaded to OneDrive and only a "ghost" file is left in its place until you open it, at which point the file is downloaded once again and the extension makes a preview image.

_[Hat tip to @digitalchet](https://github.com/maphew/svg-explorer-extension/issues/1#issuecomment-527181362) for figuring this out._

**Comment by richard-scott** [comment]
I have the same issue but its with files in Google Drive.

**Comment by taodailOryx** [comment]
+1. I love this extension; it's invaluable. It would be nice if it could work on cloud folders. I wish I knew enough to look into it.

**Comment by jeffhoward001** [comment]
We're running into the same issue, we use OneDrive like our corp network share, so this is a real bummer.

**Comment by PhilippSPOTTERON** [comment]
Same here sadly. The SVG files are saved locally, not just in the OneDrive Cloud but do not show as thumbnails in explorer on Windows 10 64bit.

**Comment by maphew** [comment]
It seems to extend beyond cloud folders. I have a folder on my local D: drive with an assortment of image types (GIF, ICO, PNG, & SVG). Thumbnails are not generated for the .svg files in this specific folder. Other folders in the same folder tree are fine. If I copy the files to another folder on the same drive thumbnails are generated.

```
D:\github\a-project\icons --> no svg thumbs
D:\new folder\icons --> yes svg thumbs
```
Deleting IconCache.db and restarting Explorer.exe doesn't change the behaviour.

If I browse to the project folder (...\a-project\icons) and then [search] for *.svg and set view mode to Large icons those same svg's do not have thumbs. HOWEVER if i change view mode to Medium icons there are icons. See screenshots below.

Perhaps there is a cached view setting somewhere in addition to `"%localappdata%\IconCache.db"` that needs to be reset. 

There isn't a Thumbs.db file in any of the folders examined here. 'Explorer >> Folder Options >> View' setting to [never create Thumbs.db files](https://www.computerhope.com/issues/ch001061.htm) is _not_ checked. Neither are the [similar group policy settings](https://www.sitepoint.com/switch-off-thumbs-db-in-windows/) configured. (That's no guarantee these settings aren't in place from another place though.)

For people reporting issues with cloud folders, I wonder if the setting "Turn off display of thumbnails and only display icons for network folders" is at play.

![2018-05-22 12_56_02-_ svg - search results in leo](https://user-images.githubusercontent.com/486200/40387521-d5303dfe-5dc1-11e8-9c57-8fc79e914d1d.png)
![2018-05-22 12_57_32-_ svg - search results in leo](https://user-images.githubusercontent.com/486200/40387519-d5146ad4-5dc1-11e8-8531-65b7e15b149b.png)
![2018-05-22 13_10_48-local group policy editor](https://user-images.githubusercontent.com/486200/40387518-d4f4d1ba-5dc1-11e8-8887-ccf580cb813e.png)

Host system: Win7-x64

**Comment by richard-scott** [comment]
I found a way to fix my black thumbnail pictures problem that may help others.
In Inkscape:

1. Load problem file and CTRL+A to select all.
2. File -> Document Properties -> Resize document to selection.
3. File -> Clean up document
4. File -> Save

And if that didn't work, cutting and pasting the objects into a new file and then doing the above on it helped too.

**Comment by darylknight** [comment]
Same issue for me on Windows 10 x64.

**Comment by jdgregson** [comment]
I am also affected by this issue, also Windows 10 x64.

I found two interesting points that others may have pointed out:
1. the thumbnails render when viewing search results of the OneDrive folder (the green check mark is still visible)
2. the thumbnails render inside a Save As dialog in the OneDrive folder (the green check mark is still visible)

I'm not sure if this extension is still under active development, but it would be fantastic if this bug is worked out. I was able to use this in my OneDrive folder in the past.

**Comment by cmgharris** [comment]
Same problem, Windows 10 x64.
In a folder within OneDrive, the thumbnails don't work. But if I copy the folder to a location outside OneDrive, it works fine.
Interestingly, when copying a new svg into the OneDrive folder, it works, and I see the image thumbnail, as long as the OneDrive status icon is showing 'still syncing' (blue circular arrows). As soon as it's synced (green tick) it reverts back to what looks like the internet explorer icon (blue 'e' with yellow trimming).

**Comment by digitalchet** [comment]
OneDrive users, If you haven't already done so, make sure you go into **Settings** and disable the **Save space and download files as you use them** option.
I had the issue where the thumbs would not show and the IE icon would show in their place, but once I disabled that option and refreshed the folder, my files and their thumbnails returned. With some files however, I've had to edit and save them before they've shown up so your results may vary.
This is simply because with this option enabled, the files are uploaded to OneDrive, leaving only a "ghost" file in its place until you open it, at which point the file is downloaded once again.
It's possible that this may not address the black background issue but anything is worth a try, right?

**Comment by cmgharris** [comment]
thanks digitalchet, this has resolved my issue :o)

**Comment by raffertyuy** [comment]
Wow, after some time of reinstalling this tool - it is actually this issue! Thanks!

**Comment by maphew** [comment]
@digitalchet thanks for finding a solution. I added it to the opening post. @cmgharris and @raffertyuy, thanks for verifying.

Closing the issue as the problem and solution happen outside the extension's purview, and is now documented.
