### ISSUE TITLE
Not working with Windows 10 19H1

### ISSUE THREAD

**Issue by sandras74** [maphew/svg-explorer-extension#13]
Hi,

I have installed the new Insider image and the extension doesn't work with the new version of Windows.

Bye,
Sandras74

**Comment by marcnewton** [comment]
I don't know what 19H1 is...
Anyway I confirm this is not working with Win 10.0.**17763** Pro x64,
Logged in as user with administrator privileges.

I cleared the thumbnail cache after installing and watched it regenerate Explorer Icons again instead of the expected thumbnails.

**Comment by sandras74** [comment]
The 19H1 was a Windows Insider version, today it is the actual version of the 10.
The SVG-explorer-extension is working with the actual Windows but not works with the OneDrive folders.

**Comment by marcnewton** [comment]
I solved my issue, It's so stupid!

On a fresh install of Windows 10 since last year `Always show icons, never thumbnails` is checked by default in Explorer's **Folder Options** in certain folders.

Uncheck the box and taadaaaa.....

For some reason this was checked in my **Pictures** folder.

![Annotation 2019-06-12 083035](https://user-images.githubusercontent.com/30183052/59331883-e5f94580-8cec-11e9-8759-88e6c601f9d1.png)

**Comment by UweKeim** [comment]
For me, the SVG images are not shown anymore since month, too.

---------

**Update:** After refreshing the icon cache as described in the readme, it works again, even with latest Windows 10 release:

```cmd
TASKKILL /IM explorer* /F
DEL "%localappdata%\IconCache.db" /A
explorer.exe
```

**Comment by sandras74** [comment]
In my Windows (18922) the 'Always show icons, never thumbnails' option unchecked by default but doesn't work.

**Comment by wrapper** [comment]
Not working in Windows 17763

**Comment by sandras74** [comment]
Works on the latest Insider fast ring release

**Comment by maphew** [comment]
Closing as it sounds like newer Insider releases are okay. (You can always re-open if this isn't the case).
