### ISSUE TITLE
Certificate revoked

### ISSUE THREAD

**Issue by Akababa** [maphew/svg-explorer-extension#29]
![image](https://user-images.githubusercontent.com/4205182/70024069-4912b900-1567-11ea-94c3-e8bb19b50a88.png)

It's blocked by windows UAC -- is this still safe?

**Comment by Akababa** [comment]
Unsigned version from https://code.google.com/archive/p/svg-explorer-extension/downloads works fine.

**Comment by maphew** [comment]
thanks @Akababa. I added the unsigned binary install programs to the Github releases: https://github.com/maphew/svg-explorer-extension/releases/tag/v0.1.1

**Comment by maphew** [comment]
Closing this, though resolving #27 and/or #28 will be the real fix (generating new install binaries from current code base).

**Comment by VA1DER** [comment]
Perhaps you want to offer some more details as to why the certificate was revoked.  A certificate revocation on a code signing certificate is a serious event.  Telling people to just move to an unsigned version doesn't address concerns over, say, why the certificate was revoked in the first place.

**Comment by tibold** [comment]
I have no clue why it was revoked.
That certificate is so old I have no access to any of it anymore.

The free certificate offering for open source code was discontinued, so I don’t actually know from where to get a new certificate cheap.

Tibold Kandrai
Software Architect & Engineer
________________________________

**Comment by VA1DER** [comment]
I would recommend Certum.  They offer open source code signing certificates for €25, which is the cheapest I know about.  Unfortunately, I don't know of any more free code signing certificates for open source developers.

**Comment by tibold** [comment]
Thanks,
I was considering that too. They were the ones that offered the free one as well.

**Comment by maphew** [comment]
perhaps CodeNotary? See ad post: https://medium.com/vchaincodenotary/developers-unite-against-the-expensive-and-cumbersome-code-signing-certificates-d54342016a64.

**Comment by VA1DER** [comment]
From what I can tell, CodeNotary is a side-channel software verification system that doesn't interface with the Windows installer.  How much you have to pay for it no one can actually see, because they are careful not to say anywhere how much you have to pay until after you sign up for the "free 30 day trial".  It [looks like](https://www.tenforums.com/tutorials/78681-add-file-hash-context-menu-windows-8-10-a.html) they have a community edition which is free to use, but I can't verify that with them.  Yet another company who thinks that "blockchain" will attract investors.  If you are going to force your users to install something to verify your signatures, why not get them to [add hash-checking to their context menu](https://www.tenforums.com/tutorials/78681-add-file-hash-context-menu-windows-8-10-a.html)? That then will work for all open source projects and not just the ones who use codenotary.
