### ISSUE TITLE
Installer: failed to start because no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by maphew** [maphew/svg-explorer-extension#36]
When running the 64 bit installer for [maphew appveyor dev release](https://ci.appveyor.com/project/maphew/svg-explorer-extension/build/artifacts) (fake v1.0.30) at the end **regsvr32** reports _"This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."_

Followed by:

> **Error**
> C:\Program Files\Dotz Softwares\SVG Explorer Extension\SVGThumbnailExtension.dll
> Unable to register the DLL/OCX: RegSvr32 failed with exit code 0xC0000409.
> Click Retry to try again, Ignore to proceed anyway (not recommended), or Abort to cancel installation.

Win10 Enterprise 1803 build 17134.1130

**Comment by maphew** [comment]
After running install program and choosing [ignore], browsing to a folder with .svg files in it, the "failed to start" error dialog reappears, and naturally there are no previews:

![image](https://user-images.githubusercontent.com/486200/71531543-03b28480-28a4-11ea-962d-7fe70106f057.png)

This is a different machine from the opening post, and using an installer from today.

**Comment by tibold** [comment]
This is a Qt thing. Some platform code is implemented in plugins. These have to be shipped with the installer and QCoreApplication has to be able to find them.
Once I got my dev environment running it should be simply to identify what doesn't like.

**Comment by tibold** [comment]
#45 should fix this issue.
Check in `Initialize` method in `Main.cpp`.

**Comment by maphew** [comment]
Getting this message still with the real v1.0 release. After the regsvr32 Qt plugin error there's a new one, _"Unable to register the DLL/OCX: RegSvr32 failed with exit code 0xC0000409"_. Or rather the message is the same but the appearance of the dialog is different.

Screenshot: https://user-images.githubusercontent.com/486200/71647380-e833e900-2caa-11ea-8662-a2d02a06c51b.png

Trying again just repeats. If I [ignore] the MS VC 2017 runtime install proceeds. At about the 60% mark it appears to stall for a long time, and then starts closing applications and rebooting the computer without warning.

**Comment by maphew** [comment]
I've now installed real v1 on 3 Win10 machines and only this one gives this error. It's a Surface Pro v4, Win10 Enterprise 1803 build 17134.1130.

**Comment by tibold** [comment]
For the restart I missed the `/norestart` flag on calling vcredist. :/

I am a bit puzzled with the exception. Is that a dev machine by any chance?

**Comment by maphew** [comment]
Very good to have the restart fixed! 

Nope, not a dev machine. Well, not a C++ dev machine. It does have Python, PyQt and some related things, but not QtCreator, Win SDK or anything like that. I'll dig through the installed list and see if something stands out. Anything in particular I should watch for?

**Comment by vmario89** [comment]
Hi, i have the exact same error message on my computer. running your extension for many years now and updated to 1.0.0. Now this happens for me the first time.

**Comment by maphew** [comment]
Fixed it! ...but not exactly sure what was the necessary ingredient. I did:

- From _"Add or remove programs"_ uninstalled half a dozen programs I don't use anymore
- Scanned list for anything obviously related to Qt (none)
- Ran CCleaner, used "easy clean" followed by "analyze registry" and applied all recommendations
- Rebooted
   - whereupon Windows also applied an Update I didn't know was pending
- Reran v1.0.0 install

At first I thought all previews were broken for all file types, because none at all were showing. Eventually I determined I needed to _'Explorer >> View >> Options'_ and de-check _' Always show icons, never thumbnails'_. I wouldn't have turned that on, was probably CCleaner.

For anyone wanting a targetted fix my hunch is that there's 1 or 2 registry keys that have the wrong permissions. Try searching for `Dotz` and/or `SVG Explorer` or `SVG Explorer Extension`.

@vmario89 let us know if any of this helps you

**Comment by tibold** [comment]
@maphew , thanks for investigating it.

I have added quick logging to the registration process so we can catch at which key does the process fail. The code is currently on a bug branch and the builds are available here: 
https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29933374/artifacts

To view the logs use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview). In the tool you can set up a filter such as `Edit`->`Filter` and type `SvgSee` in the `Include` box. Make sure the `Capture`->`Capture Win32` option is checked in the main menu.

Once the tool is running and configured, run the installer and it will be able to catch the debug messages. Here's an example screenshot:
![image](https://user-images.githubusercontent.com/1974659/71855226-b8d51000-30e0-11ea-8970-c0d81dd52088.png)

If you got the logs please paste them in here so we can see what's what.

---

On a different lead I was investigating the vcredist. It seems that the DLL registration happens __before__ vcredist is installed and the missing runtime might cause that kind of issue. However, reading the previous comment I have doubts that this is what we're seeing here. Nonetheless the order needs fixing anyway.

**Comment by DKStudio** [comment]
I caption this error from DebugView
00000001	0.00000000	[22112] ("C:/Program Files/SVG Explorer Extension/SVGThumbnailExtension.dll\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00	
00000002	0.01159570	[22112] 00\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000???\u0000?簊翿\u0000???\u0000??i\u0000\u0002\u0000\u0000\u0000麰簊翿\u0000???\u0000?簊翿\u0000直??\u0000?簊翿\u0000???\u0000??i\u0000\u0002\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000?簊翿\u0000埔\uF468\u0000\u0000?簊翿\u0000??i\u0000??i\u0000???\u0000?簊翿\u0000\u0000\u0000\u0000\u0000???\u0000??i\u0000??i\u0000??i\u0000鑑簊翿\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000???\u0000驈簊翿\u0000??i\u0000\u0000\u0000\u0000\u0000??i\u0000釙簊翿\u0000\u0000\u0000\u0000\u0000\t\u0000翿\u0000??i\u0000??i\u0000??i\u0000??i\u0000??i\u0000?簊翿\u0000???\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000??i\u0000\u0000\u0000\u0000\u0000?抒翿\u0000??i\u0000憶簊翿\u0000??i\u0000???\u0000???\u0000??i\u0000???\u0000???\u0000??i\u0000??i\u0000\u0000\u0000 \u0000?簊翿\u0000H\u0000\u0000\u0000\u0001\u0000翿\u0000??i\u0000\u0000\u0000\u0000\u0000`\u0000\u0000\u0000??３\uFFFF\uFFFF\uFFFF\uFFFF\uFFFF?簊翿\u0000慔簊翿\u0000??i\u0000\u0000?i\u0000??i\u0000\u0000TDLL\u0000\u0000\u0000??i\u0000??i\u0000??\u0000\u0000\uD997簆翿\u0000\u001COi\u0000??i\u0000??i\u0000?\u0000\u0000\u0000?\u0000\u0000\u0000巂簊翿\u0000??i\u0000??\u0000\u0000??i\u0000驈簊翿\u0000??i\u0000\u0000\u0000\u0000\u0000??i\u0000甀??\u0000??i\u0000駜簊翿\u0000\u0000\u0000\u0000\u0000驈簊翿\u0000??i\u0000\u0000\u0000\u0000\u0000??i\u0000L.DL??i\u0000駜簊翿\u0000\u0000\u0000\u0000\u0000??i\u0000\u0012?i\u0000??i\u0000NTDLL.DLL\u0000\u0000\u0000?簊翿\u0000\u0000\u0000\u0000\u0000??i\u0000\u0000??\u0000??i\u0000??i\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0080\u0000\u0000\u0000\u001C\u001C\u0000\u0000???\u0000?\uF7B3翾\u0000?\uF777翾\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000i\u0000a簆翿\u0000\u0000\u0000\u0000\u0000??i\u0000\u0000\u0000\u0000\u0000\u0000??\u0000??翿\u0000\u0000簆翿\u0000???\u0000??i\u0000\uE0F8?翿\u0000???\u0000???\u0000\u001B\u0000i\u0000?\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000?\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000\u0000\u0000?\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000??\u0000??i\u0000\u0011\u0000\u0000\u0000\uD997簆翿\u0000@\u0000")	
00000003	0.02634640	[22112] qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""	
00000004	3.50212598	[22112] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.	
00000005	3.50212598	[22112]

**Comment by tibold** [comment]
@DKStudio , which installer did you use?

The output looks like it is from the v1.0.0 release. If so could you please try the builds from this link:
https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29933374/artifacts

In the builds I linked every log line is prefixed with `SvgSee`, which is missing in this output.

The random character output was a typo that is now also fixed.

**Comment by DKStudio** [comment]
> @DKStudio , which installer did you use?
> 
> The output looks like it is from the v1.0.0 release. If so could you please try the builds from this link:
> https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29933374/artifacts
> 
> In the builds I linked every log line is prefixed with `SvgSee`, which is missing in this output.
> 
> The random character output was a typo that is now also fixed.

This software version is OK,thinks.

**Comment by alexysong** [comment]
> @DKStudio , which installer did you use?
> 
> The output looks like it is from the v1.0.0 release. If so could you please try the builds from this link:
> https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/29933374/artifacts
> 
> In the builds I linked every log line is prefixed with `SvgSee`, which is missing in this output.
> 
> The random character output was a typo that is now also fixed.

This version (1.0.19) worked on my win 10. The 1.0.0 release doesn't work, same error message.

**Comment by tibold** [comment]
Thanks for the feedback!
It seems that everyone's issue got solved, so I'll close this issue.

**Comment by Marcus888** [comment]
I had the same Qt problem! 
The version (1.0.19) worked for me too! 
The 1.0.0 release doesn't work, same error message.

Thanks!
