### ISSUE TITLE
SVG preview in compressed folders does not work

### ISSUE THREAD

**Issue by tinne** [maphew/svg-explorer-extension#89]
When I open a subfolder of a ZIP file in Windows Explorer and change the display settings to a mode which would display preview icons if unpacked, only the generic default SVG icon (IE by default) is displayed. Unpacking the same folder yields the correct view.

Can be reproduced on, e.g., [fontawesome-free-5.13.0-desktop.zip](https://github.com/FortAwesome/Font-Awesome/releases/download/5.13.0/fontawesome-free-5.13.0-desktop.zip), folder `fontawesome-free-5.13.0-desktop/svgs/solid/`.

**Comment by voxain** [comment]
As far as I know, that's how zip files always are. That's not an issue of the extension - If you put a png file inside a ZIP-Archive, it also won't render a thumbnail because that would require the file to be uncompressed first. Now if you have a folder with, let's say, 500 png icons, that's not just gonna take a while, but also will completely destroy the logic behind a compressed archive which is to save space.
I'm not a pro, but from my knowledge, this is intended behavior by the explorer - Correct me if wrong!

**Comment by tinne** [comment]
You are right.

I fell for the fact that certain image formats support embedded previews images which can be rendered in this situation, and WE does so if the image resolution fits.

Since the SVG standard does not support this (and adding support would perhaps unneccessarily increase the size of compact files) I close the ticket.
