### ISSUE TITLE
Feature Request - Check if using dark theme, and turn the icons white

### ISSUE THREAD

**Issue by dragonkey100** [maphew/svg-explorer-extension#92]
For more flexibility, I think you should get the background colour, and then get the inverse colour (instead of being locked to black or white) so that the contrast is high. Thanks.

**Comment by dragonkey100** [comment]
Note: I can see much better when the icons are selected because the background becomes much brighter.
So I think you'll have to adjust for that as well.

**Comment by mikenakis** [comment]
Let me explain what the issue is a bit better, and a possibly preferable solution.

In general, "dark mode" is very popular among people who tend to use a computer a lot (for example, programmers) and who 
also tend to want to have control over their computer instead of just accepting things the way they are. (For example, programmers.)  

As a result, (catering to popular demand,) popular IDEs have had dark mode support for a long time now, (e.g. IntelliJ IDEA, Visual Studio,) many web sites are offering dark mode, (e.g., Stackoverflow, GitHub, Slack,) many other applications support it, (e.g. Inkscape,) and even operating systems support it (e.g. Ubuntu, MacOs, Windows.) 

Of course, Dark Mode is not without its problems. Some applications do not look good in dark mode, and some have inherent issues with it. For example, in Inkscape, dark mode affects the user interface, but not the canvas, which by default remains white. To overcome this problem in Inkscape, we tend to go to "Document properties..." and in the "Background" section we select a "Background color" which is something dimmer than the full brightness of the sun glaring straight into our eyes.  Of course, we cannot make it very dim, because our images are usually icons, typically consisting of black figures on a transparent background, so if the canvas was very dark, then we would not be able to see the black figures on top of it.  So, we select some shade of grey.  Personally, I use color #696969.  Inkscape saves this color in the SVG file, in the pagecolor attribute of the <sodipodi:namedview> element.

And now we come to the SVG thumbnails explorer extension.  Unfortunately, this extension seems to be rendering the icons exactly as they are, ignoring the pagecolor setting.  There is merit in this approach, because it is objective, and it does not favor any particular SVG extension (sodipodi) over others. However, this approach is not pragmatic: all of us using dark mode in Windows are stuck with thumbnails of SVG files showing pitch black figures on an almost black background, which is illegible. 

A pragmatic solution would be to look at the pagecolor setting, and if present, honor it, because if it is present, then it is guaranteed to be the color that the user wants to see.  

This has the benefit of being independent of the OS setting, so if a user changes between dark mode and bright mode, they will not be stuck with some thumbnails having a dark background, and some thumbnails having a bright background.  The background of a thumbnail will only need to change when the actual SVG file changes, which is how the SVG extension already works.

**Comment by dragonkey100** [comment]
I guess this cannot be solved.
